-- MEMBER Table Create SQL
CREATE TABLE MEMBER
(
    MEMBER_NO    NUMBER          NOT NULL, 
    MEMBER_ID    VARCHAR2(30)    NOT NULL, 
    PW           VARCHAR2(64)    NOT NULL, 
    NAME         VARCHAR2(20)    NOT NULL, 
    EMAIL        VARCHAR2(45)    NOT NULL, 
    REGDATE      DATE            NOT NULL, 
    MANAGER      NUMBER(1)       NULL, 
    STATE        NUMBER(1)       NOT NULL, 
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_NO)
);

CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER TABLE MEMBER ADD CONSTRAINT UQ_MEMBER_EMAIL UNIQUE (EMAIL);

ALTER TABLE MEMBER ADD CONSTRAINT UQ_MEMBER_ID UNIQUE (MEMBER_ID);

-- PRODUCT Table Create SQL
CREATE TABLE PRODUCT
(
    PRODUCT_NO      VARCHAR2(30)         NOT NULL, 
    PRODUCT_NAME    VARCHAR2(100)   NOT NULL, 
    BRAND           VARCHAR2(30)    NULL, 
    PRICE           NUMBER(10)      NOT NULL, 
    IMAGE           VARCHAR2(1000)  NOT NULL,
    STATE           NUMBER(1)       NOT NULL, 
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_NO)
);

ALTER TABLE PRODUCT ADD CONSTRAINT UQ_PRODUCT_NAME UNIQUE (PRODUCT_NAME);

-- MEMBER_ADDRESS Table Create SQL
CREATE TABLE MEMBER_ADDRESS
(
    MEMBER_ADDRESS_NO    NUMBER           NOT NULL, 
    MEMBER_NO            NUMBER           NOT NULL, 
    NAME                 VARCHAR2(100)    NOT NULL, 
    ADDR1                VARCHAR2(100)    NOT NULL, 
    ADDR2                VARCHAR2(100)    NULL, 
    STATE                NUMBER(1)        NOT NULL, 
    CONSTRAINT PK_MEMBER_ADDRESS PRIMARY KEY (MEMBER_ADDRESS_NO)
);


CREATE SEQUENCE MEMBER_ADDRESS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER TABLE MEMBER_ADDRESS
    ADD CONSTRAINT FK_MEMBER_ADDRESS_MEMBER_NO_ME FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER (MEMBER_NO);


-- PRODUCT_DETAIL Table Create SQL
CREATE TABLE PRODUCT_DETAIL
(
    PRODUCT_DETAIL_NO    NUMBER           NOT NULL, 
    PRODUCT_NAME         VARCHAR2(100)    NOT NULL, 
    PRODUCT_SIZE         NUMBER(3)        NOT NULL, 
    CONSTRAINT PK_PRODUCT_DETAIL PRIMARY KEY (PRODUCT_DETAIL_NO)
);

CREATE SEQUENCE PRODUCT_DETAIL_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER TABLE PRODUCT_DETAIL
    ADD CONSTRAINT FK_PRODUCT_DETAIL_PRODUCT_NAME FOREIGN KEY (PRODUCT_NAME)
        REFERENCES PRODUCT (PRODUCT_NAME);


-- REVIEW Table Create SQL
CREATE TABLE REVIEW
(
    REVIEW_NO       NUMBER            NOT NULL, 
    MEMBER_ID       VARCHAR2(30)      NOT NULL, 
    PRODUCT_NAME    VARCHAR2(100)     NOT NULL, 
    TITLE           VARCHAR2(1000)    NOT NULL, 
    CONTENT         VARCHAR2(4000)    NOT NULL, 
    IMAGE           VARCHAR2(1000)    NULL, 
    POSTDATE        DATE              NOT NULL, 
    MODIFYDATE      DATE              NULL, 
    HIT             NUMBER            NULL,
    IP              VARCHAR2(25)      NOT NULL, 
    STATE           NUMBER(1)         NOT NULL, 
    CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_NO)
);

CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER TABLE REVIEW
    ADD CONSTRAINT FK_REVIEW_MEMBER_ID_MEMBER_MEM FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE REVIEW
    ADD CONSTRAINT FK_REVIEW_PRODUCT_NAME_PRODUCT FOREIGN KEY (PRODUCT_NAME)
        REFERENCES PRODUCT (PRODUCT_NAME);

-- NOTICE Table Create SQL
CREATE TABLE NOTICE
(
    NOTICE_NO    NUMBER            NOT NULL, 
    MEMBER_ID    VARCHAR2(30)      NOT NULL, 
    TITLE        VARCHAR2(1000)    NOT NULL, 
    CONTENT      VARCHAR2(4000)    NOT NULL, 
    POSTDATE     DATE              NOT NULL, 
    STATE        NUMBER(1)         NOT NULL, 
    CONSTRAINT PK_NOTICE PRIMARY KEY (NOTICE_NO)
);

CREATE SEQUENCE NOTICE_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER TABLE NOTICE
    ADD CONSTRAINT FK_NOTICE_MEMBER_ID_MEMBER_MEM FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID);

-- FAQ Table Create SQL
CREATE TABLE FAQ
(
    FAQ_NO       NUMBER            NOT NULL, 
    MEMBER_ID    VARCHAR2(30)      NOT NULL, 
    QUESTION     VARCHAR2(1000)    NOT NULL, 
    ANSWER       VARCHAR2(4000)    NOT NULL, 
    POSTDATE     DATE              NOT NULL, 
    STATE        NUMBER(1)         NOT NULL, 
    CONSTRAINT PK_FAQ PRIMARY KEY (FAQ_NO)
);

CREATE SEQUENCE FAQ_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER TABLE FAQ
    ADD CONSTRAINT FK_FAQ_MEMBER_ID_MEMBER_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID);

-- PRODUCT_BUY Table Create SQL
CREATE TABLE PRODUCT_BUY
(
    PRODUCT_BUY_NO       NUMBER          NOT NULL, 
    MEMBER_ID            VARCHAR2(30)    NOT NULL, 
    PRODUCT_DETAIL_NO    NUMBER          NOT NULL, 
    PRICE                NUMBER(10)      NOT NULL, 
    MEMBER_ADDRESS_NO    NUMBER          NOT NULL, 
    POSTDATE             DATE            NOT NULL, 
    BUYDATE              DATE            NULL, 
    STATE                NUMBER(1)       NOT NULL, 
    CONSTRAINT PK_PRODUCT_BUY PRIMARY KEY (PRODUCT_BUY_NO)
);

CREATE SEQUENCE PRODUCT_BUY_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER TABLE PRODUCT_BUY
    ADD CONSTRAINT FK_PRODUCT_BUY_PRODUCT_DETAIL_ FOREIGN KEY (PRODUCT_DETAIL_NO)
        REFERENCES PRODUCT_DETAIL (PRODUCT_DETAIL_NO);

ALTER TABLE PRODUCT_BUY
    ADD CONSTRAINT FK_PRODUCT_BUY_MEMBER_ID_MEMBE FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE PRODUCT_BUY
    ADD CONSTRAINT FK_PRODUCT_BUY_MEMBER_ADDRESS_ FOREIGN KEY (MEMBER_ADDRESS_NO)
        REFERENCES MEMBER_ADDRESS (MEMBER_ADDRESS_NO);


-- PRODUCT_SELL Table Create SQL
CREATE TABLE PRODUCT_SELL
(
    PRODUCT_SELL_NO      NUMBER          NOT NULL, 
    MEMBER_ID            VARCHAR2(30)    NOT NULL, 
    PRODUCT_DETAIL_NO    NUMBER          NOT NULL, 
    PRICE                NUMBER(10)      NOT NULL, 
    MEMBER_ADDRESS_NO    NUMBER          NOT NULL, 
    POSTDATE             DATE            NOT NULL, 
    SELLDATE             DATE            NULL, 
    PRODUCT_BUY_NO       NUMBER          NULL, 
    STATE                NUMBER(1)       NOT NULL, 
    CONSTRAINT PK_PRODUCT_SELL PRIMARY KEY (PRODUCT_SELL_NO)
);

CREATE SEQUENCE PRODUCT_SELL_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER TABLE PRODUCT_SELL
    ADD CONSTRAINT FK_PRODUCT_SELL_PRODUCT_DETAIL FOREIGN KEY (PRODUCT_DETAIL_NO)
        REFERENCES PRODUCT_DETAIL (PRODUCT_DETAIL_NO);

ALTER TABLE PRODUCT_SELL
    ADD CONSTRAINT FK_PRODUCT_SELL_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE PRODUCT_SELL
    ADD CONSTRAINT FK_PRODUCT_SELL_MEMBER_ADDRESS FOREIGN KEY (MEMBER_ADDRESS_NO)
        REFERENCES MEMBER_ADDRESS (MEMBER_ADDRESS_NO);

ALTER TABLE PRODUCT_SELL
    ADD CONSTRAINT FK_PRODUCT_SELL_PRODUCT_BUY FOREIGN KEY (PRODUCT_BUY_NO)
        REFERENCES PRODUCT_BUY (PRODUCT_BUY_NO);

-- ALARM Table Create SQL
CREATE TABLE ALARM
(
    ALARM_NO     NUMBER           NOT NULL, 
    MEMBER_ID    VARCHAR2(30)     NOT NULL, 
    CONTENT      VARCHAR2(300)    NOT NULL, 
    STATE        NUMBER(1)        NOT NULL, 
    CONSTRAINT PK_ALARM PRIMARY KEY (ALARM_NO)
);

CREATE SEQUENCE ALARM_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER TABLE ALARM
    ADD CONSTRAINT FK_ALARM_MEMBER_ID_MEMBER_MEMB FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID);

CREATE TABLE REVIEW_COMMENT
(
    REVIEW_COMMENT_NO    NUMBER            NOT NULL, 
    REVIEW_NO            NUMBER            NOT NULL, 
    MEMBER_ID            VARCHAR2(30)      NOT NULL, 
    CONTEXT              VARCHAR2(2000)    NOT NULL, 
    STATE                NUMBER(1)         NOT NULL, 
    PRIMARY KEY (REVIEW_COMMENT_NO)
);

CREATE SEQUENCE REVIEW_COMMENT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

ALTER TABLE REVIEW_COMMENT
    ADD CONSTRAINT FK_REVIEW_COMMENT_REVIEW_NO_RE FOREIGN KEY (REVIEW_NO)
        REFERENCES REVIEW (REVIEW_NO);
        
ALTER TABLE REVIEW_COMMENT
    ADD CONSTRAINT FK_REVIEW_COMMENT_MEMBER_ID_ME FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID);